export { default as LoginPage } from './LoginPage'
export { default as RegisterPage } from './RegisterPage'
export { default as DashboardPage } from './DashboardPage'
export { default as SubjectsPage } from './SubjectsPage'
export { default as ResultsPage } from './ResultsPage'
export { default as SettingsPage } from './SettingsPage'
